"""empty message

Revision ID: 284c06bb7d9d
Revises: 8c6ef7643eaf
Create Date: 2018-06-17 15:12:20.181433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284c06bb7d9d'
down_revision = '8c6ef7643eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
