"""empty message

Revision ID: 42352658285d
Revises: 66403ecf5fce
Create Date: 2018-05-27 00:23:13.300186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42352658285d'
down_revision = '66403ecf5fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
