"""empty message

Revision ID: 661c762df1d4
Revises: bbf6a8de7033
Create Date: 2018-05-27 02:02:26.155161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661c762df1d4'
down_revision = 'bbf6a8de7033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpm_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mr_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kpm_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
