"""empty message

Revision ID: 66403ecf5fce
Revises: f16052e671d9
Create Date: 2018-05-27 00:23:09.188190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66403ecf5fce'
down_revision = 'f16052e671d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpm_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpm_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
