"""empty message

Revision ID: 679bb998a165
Revises: 661c762df1d4
Create Date: 2018-06-17 14:52:58.196458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679bb998a165'
down_revision = '661c762df1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', sa.String(length=255), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'group')
    # ### end Alembic commands ###
