"""empty message

Revision ID: bbf6a8de7033
Revises: 42352658285d
Create Date: 2018-05-27 02:02:10.963686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf6a8de7033'
down_revision = '42352658285d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpm_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mr_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kpm_trucks', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
