"""empty message

Revision ID: f021805f30bc
Revises: 6b11b5d44230
Create Date: 2018-06-17 15:13:08.410444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f021805f30bc'
down_revision = '6b11b5d44230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
